<?php

namespace Crawler\Export;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-23 at 18:05:34.
 */
class ExportAbstractTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExportAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

}
