<?php

namespace Crawler\Import;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-23 at 18:06:06.
 */
class ImportAbstractTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ImportAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ImportAbstract;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

}
