<?php

namespace Crawler\Filters;
 use
    Symfony\Component\DependencyInjection\ContainerBuilder,
    Symfony\Component\Config\FileLocator,
    Symfony\Component\DependencyInjection\Loader\XmlFileLoader;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-23 at 18:06:00.
 */
class FilterRunnerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FilterRunner
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $servicecontainer = new ContainerBuilder();
        $loader = new XmlFileLoader($servicecontainer, new FileLocator(__DIR__.'/../../../../src/Crawler/config/'));
        $loader->load("dic.xml");
        $this->object =  $servicecontainer->get('filters');
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Crawler\Filters\FilterRunner::init
    
     */
    public function testInit()
    {
        $this->object->init();
        $list =$this->object->getFilterList();
        $this->assertNotNull($list);
    }

    /**
     * @covers Crawler\Filters\FilterRunner::getFilterList
     * 
     */
    public function testGetFilterList()
    {
        $this->object->init();
        $list =$this->object->getFilterList();
        $this->assertNotNull($list);
    }

    /**
     * @covers Crawler\Filters\FilterRunner::run
     * @todo   Implement testRun().
     */
    public function testRun()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
