<?php

namespace Crawler\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-23 at 18:03:10.
 */
class CrawlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Crawler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->dbmock = $this->getMock('DoctrineDB',array('addUrls'));
        $this->dbmock->expects($this->any())
                    ->method('addUrls')
                    ->will($this->returnArgument(0));
        $this->settings = new CrawlerSettings();

        $this->object = new Crawler($this->settings);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Crawler\Classes\Crawler::startCrawler
     * @todo   Implement testStartCrawler().
     */
    public function testStartCrawler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    public function testaddUrls()
    {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    public function testgetCurrentPage()
    {
                $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    public function testrunFilters()
    {
                $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    public function testrunTweaks()
    {
                $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    public function testsaveHtml()
    {
                $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    public function testsetCurrentPage()
    {
                $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
