<?php

namespace Crawler\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-23 at 18:04:43.
 */
class PageCrawlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PageCrawler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PageCrawler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Crawler\Classes\PageCrawler::getPageUrls
     * @todo   Implement testGetPageUrls().
     */
    public function testGetPageUrls()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PageCrawler::getPageHTML
     * @todo   Implement testGetPageHTML().
     */
    public function testGetPageHTML()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
