<?php

namespace Crawler\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-23 at 18:04:39.
 */
class PHPCurlCrawlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CurlHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CurlHelper();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::logIn
     * @todo   Implement testLogIn().
     */
    public function testLogIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::pageExists
     * @todo   Implement testPageExists().
     */
    public function testPageExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::pageStatus
     * @todo   Implement testPageStatus().
     */
    public function testPageStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::pageMoved
     * @todo   Implement testPageMoved().
     */
    public function testPageMoved()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::getRedirectLocation
     * @todo   Implement testGetRedirectLocation().
     */
    public function testGetRedirectLocation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::httpHeaders
     * @todo   Implement testHttpHeaders().
     */
    public function testHttpHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::validHtmlPage
     * @todo   Implement testValidHtmlPage().
     */
    public function testValidHtmlPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::getContent
     * @todo   Implement testGetContent().
     */
    public function testGetContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::postToPage
     * @todo   Implement testPostToPage().
     */
    public function testPostToPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::hasProtocol
     * @todo   Implement testHasProtocol().
     */
    public function testHasProtocol()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::getDomain
     * @todo   Implement testGetDomain().
     */
    public function testGetDomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::convertLink
     * @todo   Implement testConvertLink().
     */
    public function testConvertLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::getPageSize
     * @todo   Implement testGetPageSize().
     */
    public function testGetPageSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\PHPCurlCrawler::getInfo
     * @todo   Implement testGetInfo().
     */
    public function testGetInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
