<?php

namespace Crawler\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-23 at 18:04:48.
 */
class RobotsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Robots
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Robots;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Crawler\Classes\Robots::getRobotsTxt
     * @todo   Implement testGetRobotsTxt().
     */
    public function testGetRobotsTxt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\Robots::parseRobotsFile
     * @todo   Implement testParseRobotsFile().
     */
    public function testParseRobotsFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\Robots::trimItems
     * @todo   Implement testTrimItems().
     */
    public function testTrimItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\Robots::removeComments
     * @todo   Implement testRemoveComments().
     */
    public function testRemoveComments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\Robots::makeSameCase
     * @todo   Implement testMakeSameCase().
     */
    public function testMakeSameCase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\Robots::divideByUserAgents
     * @todo   Implement testDivideByUserAgents().
     */
    public function testDivideByUserAgents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
