<?php

use siteResearch\Crawler\Classes as Classes;

/**
 * Test class for CrawlerSettings.
 * Generated by PHPUnit on 2012-10-09 at 14:49:51.
 */
class CrawlerSettingsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CrawlerSettings
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Classes\CrawlerSettings();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers CrawlerSettings::setUrl

     */
    public function testSetUrl()
    {
        $this->object->setUrl("www.github.com");
        $this->assertEquals(
                "www.github.com",$this->object->getUrl(),
                'setUrl and getUrl have the same value'
        );
    }

    /**
     * @covers CrawlerSettings::setType

     */
    public function testSetType()
    {
        $this->object->setType("testType");
        $this->assertEquals("testType",$this->object->getType(),"setType and getType are the same"
        );
    }

    /**
     * @covers CrawlerSettings::setStripIndex

     */
    public function testSetStripIndex()
    {
        $this->object->setStripIndex(true);
        $this->assertEquals(true,$this->object->getStripIndex(),'setstripindex and getstripindex are true'
        );
    }

    /**
     * @covers CrawlerSettings::setStripParameters

     */
    public function testSetStripParameters()
    {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CrawlerSettings::setDb
     */
    public function testSetDb()
    {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CrawlerSettings::setFilters
     * @todo Implement testSetFilters().
     */
    public function testSetFilters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CrawlerSettings::setTweaks
     * @todo Implement testSetTweaks().
     */
    public function testSetTweaks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CrawlerSettings::setCurl
     * @todo Implement testSetCurl().
     */
    public function testSetCurl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CrawlerSettings::getUrl
     */
    public function testGetUrl()
    {
        $this->object->setUrl("www.github.com");

        $this->assertEquals("www.github.com",$this->object->getUrl(),
                'setUrl and getUrl are equal to www.github.com'
        );
    }

    /**
     * @covers CrawlerSettings::getType
     * @todo Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CrawlerSettings::getStripIndex
     * @todo Implement testGetStripIndex().
     */
    public function testGetStripIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CrawlerSettings::getStripParameters
     * @todo Implement testGetStripParameters().
     */
    public function testGetStripParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CrawlerSettings::getDb
     * @todo Implement testGetDb().
     */
    public function testGetDb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CrawlerSettings::getFilters
     * @todo Implement testGetFilters().
     */
    public function testGetFilters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CrawlerSettings::getTweaks
     * @todo Implement testGetTweaks().
     */
    public function testGetTweaks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CrawlerSettings::getCurl
     * @todo Implement testGetCurl().
     */
    public function testGetCurl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
