<?php

use siteResearch\Crawler\Classes as Classes;

/**
 * Test class for Crawler.
 * Generated by PHPUnit on 2012-10-09 at 14:49:52.
 */
class CrawlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Crawler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @todo mock settings object
     */
    protected function setUp()
    {
        $this->settings = new Classes\CrawlerSettings();
        $this->object = new Classes\Crawler();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Crawler::getCurrent_page
     * @todo Implement testGetCurrent_page().
     */
    public function testGetCurrent_page()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler::setCurrent_page
     * @todo Implement testSetCurrent_page().
     */
    public function testSetCurrent_page()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler::startCrawler
     * @todo Implement testStartCrawler().
     */
    public function testStartCrawler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler::addUrls
     * @todo Implement testAddUrls().
     */
    public function testAddUrls()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
