<?php

use siteResearch\Crawler\Classes as Classes;

/**
 * Test class for DBPDO.
 * Generated by PHPUnit on 2012-10-09 at 14:49:52.
 */
class DBPDOTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DB_PDO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Classes\DBPDO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DB_PDO::quoteArray
     * @todo Implement testQuoteArray().
     */
    public function testQuoteArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_PDO::getColumnNames
     * @todo Implement testGetColumnNames().
     */
    public function testGetColumnNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_PDO::help
     * @todo Implement testHelp().
     */
    public function testHelp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
