<?php

use siteResearch\Crawler\Classes as Classes;

/**
 * Test class for FilterFactory.
 * Generated by PHPUnit on 2012-10-09 at 14:49:52.
 */
class FilterFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FilterFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Classes\FilterFactory();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FilterFactory::init
     * @todo Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FilterFactory::getFilterList
     * @todo Implement testGetFilterList().
     */
    public function testGetFilterList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
