<?php

use siteResearch\Crawler\Classes as Classes;

/**
 * Test class for PageCrawler.
 * Generated by PHPUnit on 2012-10-09 at 14:49:53.
 */
class PageCrawlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PageCrawler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Classes\PageCrawler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers PageCrawler::getPageUrls
     * @todo Implement testGetPageUrls().
     */
    public function testGetPageUrls()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
