<?php

use siteResearch\Crawler\Classes as Classes;

/**
 * Test class for PHP_Curl_Crawler.
 * Generated by PHPUnit on 2012-10-09 at 14:49:52.
 */
class PHPCurlCrawlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PHP_Curl_Crawler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Classes\PHPCurlCrawler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers PHP_Curl_Crawler::close
     * @todo Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::init
     * @todo Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::logIn
     * @todo Implement testLogIn().
     */
    public function testLogIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::pageExists
     * @todo Implement testPageExists().
     */
    public function testPageExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::pageStatus
     * @todo Implement testPageStatus().
     */
    public function testPageStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::pageMoved
     * @todo Implement testPageMoved().
     */
    public function testPageMoved()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::getRedirectLocation
     * @todo Implement testGetRedirectLocation().
     */
    public function testGetRedirectLocation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::httpHeaders
     * @todo Implement testHttpHeaders().
     */
    public function testHttpHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::getContent
     * @todo Implement testGetContent().
     */
    public function testGetContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::postToPage
     * @todo Implement testPostToPage().
     */
    public function testPostToPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::hasProtocol
     * @todo Implement testHasProtocol().
     */
    public function testHasProtocol()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::getDomain
     * @todo Implement testGetDomain().
     */
    public function testGetDomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::convertLink
     * @todo Implement testConvertLink().
     */
    public function testConvertLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::getPageSize
     * @todo Implement testGetPageSize().
     */
    public function testGetPageSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Curl_Crawler::getInfo
     * @todo Implement testGetInfo().
     */
    public function testGetInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
