<?php

use siteResearch\Crawler\Classes;

/**
 * Test class for simple_html_dom_node.
 * Generated by PHPUnit on 2012-10-09 at 14:49:52.
 */
class simple_html_dom_nodeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var simple_html_dom_node
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new simple_html_dom_node;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers simple_html_dom_node::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::__toString
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::clear
     * @todo Implement testClear().
     */
    public function testClear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::dump
     * @todo Implement testDump().
     */
    public function testDump()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::dump_node
     * @todo Implement testDump_node().
     */
    public function testDump_node()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::parent
     * @todo Implement testParent().
     */
    public function testParent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::children
     * @todo Implement testChildren().
     */
    public function testChildren()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::first_child
     * @todo Implement testFirst_child().
     */
    public function testFirst_child()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::last_child
     * @todo Implement testLast_child().
     */
    public function testLast_child()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::next_sibling
     * @todo Implement testNext_sibling().
     */
    public function testNext_sibling()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::prev_sibling
     * @todo Implement testPrev_sibling().
     */
    public function testPrev_sibling()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::find_ancestor_tag
     * @todo Implement testFind_ancestor_tag().
     */
    public function testFind_ancestor_tag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::innertext
     * @todo Implement testInnertext().
     */
    public function testInnertext()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::outertext
     * @todo Implement testOutertext().
     */
    public function testOutertext()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::text
     * @todo Implement testText().
     */
    public function testText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::xmltext
     * @todo Implement testXmltext().
     */
    public function testXmltext()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::makeup
     * @todo Implement testMakeup().
     */
    public function testMakeup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::find
     * @todo Implement testFind().
     */
    public function testFind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::__get
     * @todo Implement test__get().
     */
    public function test__get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::__set
     * @todo Implement test__set().
     */
    public function test__set()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::__isset
     * @todo Implement test__isset().
     */
    public function test__isset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::__unset
     * @todo Implement test__unset().
     */
    public function test__unset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::convert_text
     * @todo Implement testConvert_text().
     */
    public function testConvert_text()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::is_utf8
     * @todo Implement testIs_utf8().
     */
    public function testIs_utf8()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::getAllAttributes
     * @todo Implement testGetAllAttributes().
     */
    public function testGetAllAttributes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::getAttribute
     * @todo Implement testGetAttribute().
     */
    public function testGetAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::setAttribute
     * @todo Implement testSetAttribute().
     */
    public function testSetAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::hasAttribute
     * @todo Implement testHasAttribute().
     */
    public function testHasAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::removeAttribute
     * @todo Implement testRemoveAttribute().
     */
    public function testRemoveAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::getElementById
     * @todo Implement testGetElementById().
     */
    public function testGetElementById()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::getElementsById
     * @todo Implement testGetElementsById().
     */
    public function testGetElementsById()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::getElementByTagName
     * @todo Implement testGetElementByTagName().
     */
    public function testGetElementByTagName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::getElementsByTagName
     * @todo Implement testGetElementsByTagName().
     */
    public function testGetElementsByTagName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::parentNode
     * @todo Implement testParentNode().
     */
    public function testParentNode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::childNodes
     * @todo Implement testChildNodes().
     */
    public function testChildNodes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::firstChild
     * @todo Implement testFirstChild().
     */
    public function testFirstChild()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::lastChild
     * @todo Implement testLastChild().
     */
    public function testLastChild()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::nextSibling
     * @todo Implement testNextSibling().
     */
    public function testNextSibling()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers simple_html_dom_node::previousSibling
     * @todo Implement testPreviousSibling().
     */
    public function testPreviousSibling()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
