<?php

use siteResearch\Crawler\Classes;

/**
 * Test class for TweakFactory.
 * Generated by PHPUnit on 2012-10-09 at 14:49:53.
 */
class TweakFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TweakFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TweakFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TweakFactory::init
     * @todo Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TweakFactory::getTweakList
     * @todo Implement testGetTweakList().
     */
    public function testGetTweakList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
