<?php

namespace siteResearch\Crawler\Tweaks;

/**
 * Test class for KeepOnlyPages.
 * Generated by PHPUnit on 2012-10-09 at 15:00:51.
 */
class KeepOnlyPagesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var KeepOnlyPages
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new KeepOnlyPages;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers KeepOnlyPages::tweak
     * @todo Implement testTweak().
     */
    public function testTweak()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
