<?php

namespace siteResearch\Crawler\Tweaks;

/**
 * Test class for RemoveParameters.
 * Generated by PHPUnit on 2012-10-09 at 15:00:51.
 */
class RemoveParametersTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RemoveParameters
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RemoveParameters;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers RemoveParameters::tweak

     */
    public function testTweak()
    {
        $testarray= array("www.bbc.co.uk/index.php?weather=true","www.bbc.co.uk/index.php?sports=true");
        $resultarray = array("www.bbc.co.uk/index.php","www.bbc.co.uk/index.php");
        $this->object->tweak($testarray);
        $this->assertEquals($resultarray,$testarray,'parameters have been removed.'
        );
    }

}
