<?php

namespace siteResearch\Crawler\Tweaks;

/**
 * Test class for RemoveDuplicates.
 * Generated by PHPUnit on 2012-10-09 at 15:00:06.
 */
class RemoveDuplicatesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RemoveDuplicates
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RemoveDuplicates;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers RemoveDuplicates::tweak

     */
    public function testTweak()
    {
        $testarray = array("one", "two", "two", "five");
        $expectedresult = array("one", "two", "five");
        $result = $this->object->Tweak($testarray);
        $this->assertEquals($result, $expectedresult, "array test");
    }

}
