<?php

namespace siteResearch\Crawler\Tweaks;

/**
 * Test class for StripHash.
 * Generated by PHPUnit on 2012-10-09 at 15:00:52.
 */
class StripHashTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var StripHash
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StripHash;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers StripHash::tweak

     */
    public function testTweak()
    {
        $testarray = array("www.bbc.co.uk/index.php#sports","www.bbc.co.uk/index.php#weather");
        $resultarray = array("www.bbc.co.uk/index.php","www.bbc.co.uk/index.php");
        $this->object->tweak($testarray);
        $this->assertEquals($resultarray,$testarray,'hash has been removed'
        );
    }

}
