<?php

namespace siteResearch\Crawler\Tweaks;

/**
 * Test class for StripIndex.
 * Generated by PHPUnit on 2012-10-09 at 15:00:52.
 */
class StripIndexTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var StripIndex
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StripIndex;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers StripIndex::tweak

     */
    public function testTweak()
    {
        $testarray = array("www.github.com/index.php","www.bbc.co.uk/index.html");
        $resultarray = array("www.github.com/","www.bbc.co.uk/");
        $this->object->tweak($testarray);
        $this->assertEquals($testarray,$resultarray ,'index has been removed'
        );
    }

}
