<?php

namespace Crawler\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-12-12 at 21:51:18.
 */
class CrawlerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Crawler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Crawler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Crawler\Classes\Crawler::getCurrent_page
     * @todo   Implement testGetCurrent_page().
     */
    public function testGetCurrent_page() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\Crawler::setCurrent_page
     * @todo   Implement testSetCurrent_page().
     */
    public function testSetCurrent_page() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\Crawler::startCrawler
     * @todo   Implement testStartCrawler().
     */
    public function testStartCrawler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Crawler\Classes\Crawler::addUrls
     * @todo   Implement testAddUrls().
     */
    public function testAddUrls() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
